name: Deploy 2 Angular apps (subcarpetas) to GitHub Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps (primerProyecto)
        working-directory: primerProyecto
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi

      - name: Build (primerProyecto)
        working-directory: primerProyecto
        run: |
          REPO_NAME=${GITHUB_REPOSITORY#*/}
          npm run build -- \
            --configuration=production \
            --base-href="/$REPO_NAME/primerProyecto/"
          # SPA fallback
          cp dist/primer-proyecto/index.html dist/primer-proyecto/404.html

      - name: Install deps (proyectoFinal)
        working-directory: proyectoFinal
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi

      - name: Build (proyectoFinal)
        working-directory: proyectoFinal
        run: |
          REPO_NAME=${GITHUB_REPOSITORY#*/}
          npm run build -- \
            --configuration=production \
            --base-href="/$REPO_NAME/proyectoFinal/"
          # SPA fallback
          cp dist/primer-proyecto/index.html dist/primer-proyecto/404.html

      - name: Prepare combined artifact
        run: |
          mkdir -p site/primerProyecto site/proyectoFinal
          cp -r primerProyecto/dist/primer-proyecto/* site/primerProyecto/
          cp -r proyectoFinal/dist/primer-proyecto/* site/proyectoFinal/
          # índice simple opcional
          cat > site/index.html <<'HTML'
          <!doctype html><meta charset="utf-8">
          <title>Apps</title>
          <h1>Mis apps</h1>
          <ul>
            <li><a href="./primerProyecto/">primerProyecto</a></li>
            <li><a href="./proyectoFinal/">proyectoFinal</a></li>
          </ul>
          HTML

      - uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/deploy-pages@v4
